version: '2'

services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    user: '104'
    volumes:
      - "./04/provisioning:/etc/grafana/provisioning"
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - "./05/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./03/data:/prometheus"
      - "./05/alert.rules.yml:/etc/prometheus/alert.rules.yml"
  alertmanager:
      image: prom/alertmanager
      restart: unless-stopped
      ports:
        - "9093:9093"
      volumes:
        - "./05/config:/config"
        - "./05/data:/data"
      command: --config.file=/config/alertmanager.yml --log.level=debug
