version: '2'

services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    user: '104'
    volumes:
      - /Users/ferreirad/Documents/Jobs/TI/Ada/Aulas/DE-OP-012-Observability/04/provisioning:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - /Users/ferreirad/Documents/Jobs/TI/Ada/Aulas/DE-OP-012-Observability/05/prometheus.yml:/etc/prometheus/prometheus.yml
      - /Users/ferreirad/Documents/Jobs/TI/Ada/Aulas/DE-OP-012-Observability/03/data:/prometheus
      - /Users/ferreirad/Documents/Jobs/TI/Ada/Aulas/DE-OP-012-Observability/05/alert.rules.yml:/etc/prometheus/alert.rules.yml
  alertmanager:
      image: prom/alertmanager
      restart: unless-stopped
      ports:
        - "9093:9093"
      volumes:
        - /Users/ferreirad/Documents/Jobs/TI/Ada/Aulas/DE-OP-012-Observability/05/config:/config
        - /Users/ferreirad/Documents/Jobs/TI/Ada/Aulas/DE-OP-012-Observability/05/data:/data
      command: --config.file=/config/alertmanager.yml --log.level=debug
