version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=letscode%
